Project.PL/Areas/Admin/ViewModels/Service/ServiceDetailsVM.cs
namespace Project.PL.Areas.Admin.ViewModels.Service
{
    public class ServiceDetailsVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }

        public DateTime CreatedAt { get; set; }
    }
}

Project.PL/Areas/Admin/ViewModels/Service/ServiceFormVM.cs
namespace Project.PL.Areas.Admin.ViewModels.Service
{
    public class ServiceFormVM
    {

        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Project.PL/Areas/Admin/ViewModels/Service/ServiceVM.cs
namespace Project.PL.Areas.Admin.ViewModels.Service
{
    public class ServiceVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }


    }
}

Project.PL/Models/ErrorViewModel.cs
namespace Project.PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project.PL/Areas/Admin/Controllers/ServiceController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Project.DAl.Data;
using Project.PL.Areas.Admin.ViewModels.Service;
using Project_.DAL.Models;

namespace Project.PL.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class ServiceController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;

        public ServiceController(ApplicationDbContext context ,IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var serr = context.Services.ToList();
            var ServiceVM = mapper.Map<IEnumerable<ServiceVM>>(serr);
            return View(ServiceVM);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ServiceFormVM vm)
        {

            if(ModelState.IsValid)
            {
                var ser = mapper.Map<Service>(vm);
                context.Add(ser);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(vm);
        }

        [HttpGet]

        public IActionResult Details(int id) {
            var x = context.Services.Find(id);
            if(x == null)
            {
                return NotFound();
            }
           
            
            return View(mapper.Map<ServiceDetailsVM>(x));

        }
        [HttpGet]
        public IActionResult Delete(int id) {
            var x = context.Services.Find(id);
            if (x == null)
            {
                return NotFound();
            }
            return View(mapper.Map<ServiceVM>(x));
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmation(int id)
        {
            var service = context.Services.Find(id);

            if (service is null)
            {
                return RedirectToAction(nameof(Index));
            }

            context.Services.Remove(service);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(int id) {
            var x = context.Services.Find(id);
            if (x == null)
            {
                return NotFound();
            }
            return View(mapper.Map<ServiceDetailsVM>(x));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ServiceDetailsVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = context.Services.Find(model.Id);
            if (service == null)
            {
                return NotFound();
            }

            service.Name = model.Name;
            service.Description = model.Description;
            service.IsDeleted = model.IsDeleted;

            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

    }
}

Project.PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Project.PL.Models;
using System.Diagnostics;

namespace Project.PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project.PL/Areas/Admin/Views/Service/Create.cshtml
@model ServiceFormVM
@section Header {
    Service
}


<div class="col-md-12">
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Create </h3>
    </div>

        <form asp-controller="Service" asp-action="Create">
        <div class="card-body">
            <div class="form-group">
                <label asp-for="Name"> </label>
                    <input asp-for="Name" class="form-control" placeholder="Enter name">
            </div>
                <div class="form-group">
                    <label asp-for="Description"> </label>
                    <input asp-for="Description" class="form-control" placeholder="Enter Description">
                </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
</div>

Project.PL/Areas/Admin/Views/Service/Delete.cshtml
@model ServiceVM
@section Header {
   Delete Service
}
<div class="card card-danger">
    <div class="card-header">
        <h3 class="card-title"> Delete Confirmation </h3>
    </div>

    <div class="card-body">
        <p>are you sure to want to delete @Model.Name Service ?</p>
    </div>

    <div class="card-footer">
        <form asp-controller="Service" asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <button type="Submit" class="btn btn-danger"> Delete </button>
            <a asp-controller="Service" asp-action="Index" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>

Project.PL/Areas/Admin/Views/Service/Details.cshtml
@model ServiceDetailsVM
@section Header {
   Details Service
}

<div class="col-md-12">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">@Model.Name</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>IsDeleted</th>
                            <th>CreatedAt</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.Description</td>
                            <td>@(Model.IsDeleted ? "Is Deleted" : "Active")</td>
                            <td>@Model.CreatedAt</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- زر الرجوع إلى الفهرس -->
    <div class="mt-3">
        <a asp-controller="Service" asp-action="Index" class="btn btn-secondary">Back to Index</a>
    </div>
</div>

Project.PL/Areas/Admin/Views/Service/Edit.cshtml
@model ServiceDetailsVM

@section Header {
    <h2>Edit Service</h2>
}

<div class="col-md-12">
    <div>
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">General</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <form asp-action="Edit" asp-controller="Service" >
                    <div class="form-group">
                        <label asp-for="Name">Service Name</label>
                        <input asp-for="Name" class="form-control" value="@Model.Name" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Description">Service Description</label>
                        <textarea asp-for="Description" class="form-control" rows="4">@Model.Description</textarea>
                    </div>
                    <div class="form-group">
                        <label>Status</label><br />
                        <div class="form-check">
                            <input type="radio" class="form-check-input" value="false" id="active" name="IsDeleted"
                            @(Model.IsDeleted == false ? "checked" : "") />
                            <label class="form-check-label" for="active">Active</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" class="form-check-input" value="true" id="deleted" name="IsDeleted"
                            @(Model.IsDeleted == true ? "checked" : "") />
                            <label class="form-check-label" for="deleted">Deleted</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                    <a asp-controller="Service" asp-action="Index" class="btn btn-secondary">Cancel</a>

                </form>
            </div>
        </div>
    </div>
</div>

Project.PL/Areas/Admin/Views/Service/Index.cshtml
@model IEnumerable<ServiceVM>

@section Header {
    <h2>Service Management</h2>
}

<div class="mb-3">
    <a class="btn btn-primary text-white" asp-area="Admin" asp-controller="Service" asp-action="Create">
        <i class="fa fa-plus"></i> Create New Service
    </a>
</div>

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Show All Services</h3>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@(item.IsDeleted ? "Deleted" : "Active")</td>
                            <td>
                                <a class="btn btn-warning btn-sm" asp-route-id="@item.Id" asp-controller="Service" asp-action="Edit">
                                    <i class="fa fa-edit"></i> Edit
                                </a>
                                <a class="btn btn-info btn-sm" asp-route-id="@item.Id" asp-controller="Service" asp-action="Details">
                                    <i class="fa fa-info-circle"></i> Details
                                </a>
                                <a class="btn btn-danger btn-sm" asp-route-id="@item.Id" asp-controller="Service" asp-action="Delete">
                                    <i class="fa fa-trash"></i> Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Project.PL/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="_header" />
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

        <partial name="_navbar" />
  <!-- Main Sidebar Container -->
        <partial name="_aside"/>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
                            <h1 class="m-0">@RenderSection("Header", required: true)</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Starter Page</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
                        @RenderBody()

          
            </div>

          </div>
         
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
            <partial name="_footer"/>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
    <partial name="_script" />

</body>
</html>

Project.PL/Areas/Admin/Views/Shared/_aside.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/Admin/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/Admin/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Alexander Pierce</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Starter Pages
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link active">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Active Page</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Inactive Page</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Service" asp-action="Index" class="nav-link">
                        <i class="nav-icon  fa fa-hands-helping"></i>
                        <p>
                            Service
                            <span class="right badge badge-danger">New</span>
                        </p>
                    </a>
                   

                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

Project.PL/Areas/Admin/Views/Shared/_footer.cshtml
<!-- To the right -->
<div class="float-right d-none d-sm-inline">
    Anything you want
</div>
<!-- Default to the left -->
<strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.

Project.PL/Areas/Admin/Views/Shared/_header.cshtml
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AdminLTE 3 | Starter</title>

<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="~/Admin/plugins/fontawesome-free/css/all.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="~/Admin/css/adminlte.min.css">

Project.PL/Areas/Admin/Views/Shared/_navbar.cshtml
 <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/Admin/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/Admin/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/Admin/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

Project.PL/Areas/Admin/Views/Shared/_script.cshtml
<!-- jQuery -->
<script src="~/Admin/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="~/Admin/js/adminlte.min.js"></script>

Project.PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Project.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Service" asp-action="index">Service</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Project.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>